$(document).ready(function(){
	console.log('hello!');
	$("#First_Name").hide();
	$("#Last_Name").hide();
	$("#Address").hide();
	$("#FOUR").hide();
	$("button").click(function(){
		$("#First_Name").fadeIn("slow");
		$("#Last_Name").fadeIn("slow");
		$("#Address").fadeIn("slow");
		$("#FOUR").fadeIn("slow");
  });
}); 
